# Generated by Django 5.0.6 on 2024-06-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_events_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
