# Generated by Django 5.0.6 on 2024-06-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='secret_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
