# Generated by Django 5.0.6 on 2024-07-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_user_age_user_country_user_pincode_user_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
    ]
