# Generated by Django 5.0.6 on 2024-07-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0007_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
    ]
