# Generated by Django 5.0.6 on 2024-06-29 06:41

import UserPosts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0002_comments_community_posts_community_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
        migrations.AddField(
            model_name='posts',
            name='media',
            field=models.FileField(default='', upload_to=UserPosts.models.upload_loc),
        ),
    ]
