# Generated by Django 5.0.6 on 2024-06-29 06:43

import UserPosts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communities', '0001_initial'),
        ('UserPosts', '0003_remove_posts_image_posts_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media', models.FileField(default='', upload_to=UserPosts.models.upload_loc)),
                ('description', models.TextField(max_length=500)),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserPosts.userposts'),
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
