# Generated by Django 5.0.6 on 2024-06-29 06:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Communities', '0001_initial'),
        ('UserPosts', '0004_userposts_alter_comments_post_delete_posts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPosts',
            new_name='UserPost',
        ),
    ]
