# Generated by Django 5.0.6 on 2024-06-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpost',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
