# Generated by Django 5.0.6 on 2024-06-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPosts', '0002_publicpost_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicpost',
            name='community',
        ),
    ]
