# Generated by Django 5.0.6 on 2024-07-07 06:35

import PublicPosts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPosts', '0003_remove_publicpost_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicpost',
            name='media',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media', models.FileField(upload_to=PublicPosts.models.upload_loc)),
                ('public_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PublicPosts.publicpost')),
            ],
        ),
    ]
